server:
  port: 8086

spring:
  application:
    name: backbase
  output:
    ansi:
      enabled: ALWAYS

  datasource:
   url: jdbc:postgresql://localhost:5433/postgres
   username: postgres
   password: abc
  jpa:
   show-sql: true
   generate-ddl=: false

  liquibase:
    change-log: classpath:db.changelog/liquibase-changeLog.xml





